#!/usr/bin/env python3
"""Convert a folder of images into a C header of RGB565 TFT animation frames.

Each frame is a WIDTH x HEIGHT (default 240x240) color bitmap for use with
Adafruit_ST7789's drawRGBBitmap(). Pixels are packed as 16-bit RGB565
(5 bits red, 6 bits green, 5 bits blue), row-major, no padding.

Usage:
    # Convert real images (needs Pillow: pip install pillow):
    python3 tools/convert_frames.py assets/frames

    # Phase 4 emotion faces (assets/faces/{positive,neutral,sad,angry,surprised}/):
    python3 tools/convert_frames.py --faces assets/faces

    # Generate 2 procedural placeholder frames (no Pillow required):
    python3 tools/convert_frames.py --placeholder

The header is written to include/animation_frames.h by default.
"""

import argparse
import os
import sys

WIDTH = 240
HEIGHT = 240
FRAME_PIXELS = WIDTH * HEIGHT
FRAME_BYTES = FRAME_PIXELS * 2  # uint16_t per pixel

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_OUTPUT = os.path.join(PROJECT_ROOT, "include", "animation_frames.h")

IMAGE_EXTS = {".png", ".jpg", ".jpeg", ".bmp", ".gif"}
FACE_EMOTIONS = ("positive", "neutral", "sad", "angry", "surprised")


def rgb888_to_rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def pixels_to_frame(get_rgb):
    """Pack a `get_rgb(x, y) -> (r, g, b)` function into an RGB565 frame."""
    frame = [0] * FRAME_PIXELS
    for y in range(HEIGHT):
        row_base = y * WIDTH
        for x in range(WIDTH):
            r, g, b = get_rgb(x, y)
            frame[row_base + x] = rgb888_to_rgb565(r, g, b)
    return frame


def load_image_frames(folder):
    try:
        from PIL import Image
    except ImportError:
        sys.exit(
            "Pillow is required to convert images. Install it with:\n"
            "  python3 -m pip install --user --break-system-packages pillow\n"
            "Or generate placeholder frames with: --placeholder"
        )

    names = sorted(
        n for n in os.listdir(folder)
        if os.path.splitext(n)[1].lower() in IMAGE_EXTS
    )
    if not names:
        sys.exit(f"No image files found in {folder} (looked for {sorted(IMAGE_EXTS)}).")

    frames = []
    for name in names:
        path = os.path.join(folder, name)
        img = Image.open(path).convert("RGB")
        # Fit into WIDTHxHEIGHT while preserving aspect, pad with black.
        img.thumbnail((WIDTH, HEIGHT))
        canvas = Image.new("RGB", (WIDTH, HEIGHT), (0, 0, 0))
        canvas.paste(img, ((WIDTH - img.width) // 2, (HEIGHT - img.height) // 2))
        px = canvas.load()

        def get_rgb(x, y, _px=px):
            return _px[x, y]

        frames.append((os.path.splitext(name)[0], pixels_to_frame(get_rgb)))
    return frames


def placeholder_frames():
    """Two simple, visibly different procedural color frames (no Pillow needed)."""
    cx, cy = WIDTH // 2, HEIGHT // 2

    def frame_red_disc(x, y):
        dx, dy = x - cx, y - cy
        return (200, 30, 30) if dx * dx + dy * dy <= (WIDTH // 3) ** 2 else (0, 0, 0)

    def frame_blue_ring(x, y):
        dx, dy = x - cx, y - cy
        d2 = dx * dx + dy * dy
        inner, outer = (WIDTH // 4) ** 2, (WIDTH // 3) ** 2
        return (30, 60, 220) if inner <= d2 <= outer else (0, 0, 0)

    return [
        ("placeholder0", pixels_to_frame(frame_red_disc)),
        ("placeholder1", pixels_to_frame(frame_blue_ring)),
    ]


def load_face_sets(faces_root):
    """Load assets/faces/<emotion>/*.png in FACE_EMOTIONS order."""
    packed = []
    per_emotion = None
    for emotion in FACE_EMOTIONS:
        folder = os.path.join(faces_root, emotion)
        if not os.path.isdir(folder):
            sys.exit(f"Missing emotion folder: {folder}")
        frames = load_image_frames(folder)
        if per_emotion is None:
            per_emotion = len(frames)
        elif len(frames) != per_emotion:
            sys.exit(
                f"{folder} has {len(frames)} frames, expected {per_emotion} "
                f"(same count for every emotion)."
            )
        for name, data in frames:
            packed.append((f"{emotion}/{name}", data))
    return packed, per_emotion


def write_header(frames, output_path, faces_per_emotion=None):
    lines = []
    lines.append("#pragma once")
    lines.append("")
    lines.append("// Auto-generated by tools/convert_frames.py. Do not edit by hand.")
    lines.append("// RGB565 TFT animation frames for Adafruit_ST7789 drawRGBBitmap().")
    lines.append("")
    lines.append("#include <Arduino.h>")
    lines.append("")
    lines.append(f"#define ANIM_FRAME_WIDTH {WIDTH}")
    lines.append(f"#define ANIM_FRAME_HEIGHT {HEIGHT}")
    lines.append(f"#define ANIM_FRAME_COUNT {len(frames)}")
    if faces_per_emotion:
        lines.append(f"#define ANIM_EMOTION_COUNT {len(FACE_EMOTIONS)}")
        lines.append(f"#define ANIM_FRAMES_PER_EMOTION {faces_per_emotion}")
        lines.append("")
        lines.append("enum AnimEmotion {")
        for i, name in enumerate(FACE_EMOTIONS):
            lines.append(f"  ANIM_EMOTION_{name.upper()} = {i},")
        lines.append("};")
    lines.append("")

    for i, (name, data) in enumerate(frames):
        lines.append(f"// frame {i}: {name}")
        lines.append(f"static const uint16_t PROGMEM animFrame{i}[{FRAME_PIXELS}] = {{")
        for row in range(0, len(data), 12):
            chunk = data[row:row + 12]
            hex_words = ", ".join(f"0x{v:04X}" for v in chunk)
            lines.append(f"  {hex_words},")
        lines.append("};")
        lines.append("")

    lines.append("static const uint16_t* const animFrames[ANIM_FRAME_COUNT] = {")
    lines.append("  " + ", ".join(f"animFrame{i}" for i in range(len(frames))))
    lines.append("};")
    lines.append("")
    if faces_per_emotion:
        lines.append(
            "static const uint16_t* const "
            "animEmotionFrames[ANIM_EMOTION_COUNT][ANIM_FRAMES_PER_EMOTION] = {"
        )
        for e, name in enumerate(FACE_EMOTIONS):
            start = e * faces_per_emotion
            refs = ", ".join(f"animFrame{start + i}" for i in range(faces_per_emotion))
            lines.append(f"  {{ {refs} }},  // {name}")
        lines.append("};")
        lines.append("")

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    total_bytes = len(frames) * FRAME_BYTES
    print(
        f"Wrote {len(frames)} frame(s) ({FRAME_BYTES} bytes each, "
        f"~{total_bytes / (1024 * 1024):.2f} MB total) -> {output_path}"
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("folder", nargs="?", help="Folder of images (sorted by filename).")
    parser.add_argument(
        "--faces",
        metavar="DIR",
        help="Emotion-face root (subfolders positive/neutral/sad/angry/surprised).",
    )
    parser.add_argument("--placeholder", action="store_true", help="Generate 2 procedural placeholder frames (no Pillow).")
    parser.add_argument("-o", "--output", default=DEFAULT_OUTPUT, help=f"Output header path (default: {DEFAULT_OUTPUT}).")
    args = parser.parse_args()

    faces_per_emotion = None
    if args.placeholder:
        frames = placeholder_frames()
    elif args.faces:
        frames, faces_per_emotion = load_face_sets(args.faces)
    elif args.folder:
        frames = load_image_frames(args.folder)
    else:
        parser.error("Provide an image folder, --faces DIR, or --placeholder.")

    write_header(frames, args.output, faces_per_emotion=faces_per_emotion)


if __name__ == "__main__":
    main()
